### ISSUE TITLE
Invalid player data 

### ISSUE THREAD

**Issue by A-Pedraja** [maxomatic458/playit-minecraft-mod#2]
Fabric 1.20.1, the only mods in the server are fabric-api 0.86.0 and playitgg unofficial, Invalid Player Data appears every time i want to enter to the server.

Here is the log:

[01:27:05 INFO]: connecting to minecraft server at localhost/127.0.0.1:25565
[01:27:05 INFO]: connected to local minecraft server
[01:27:07 INFO]: UUID of player _Zulphiro is 9a4752ef-5c16-4d88-b245-11ea2d7c9f5b
[01:27:07 INFO]: _Zulphiro[/127.0.0.1:55208] logged in with entity id 131 at (-6.5, 96.0, 26.5)
[01:27:07 ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "com.mojang.authlib.GameProfile.getId()" because the return value of "net.minecraft.server.MinecraftServer.method_43824()" is null
	at gg.playit.playitfabric.PlayitFabric.onPlayerJoinDedicated(PlayitFabric.java:120) ~[playit-fabric-1.3.0-1.20.X.jar:?]
	at gg.playit.playitfabric.PlayitFabric.lambda$onInitializeServer$0(PlayitFabric.java:51) ~[playit-fabric-1.3.0-1.20.X.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.3.9+b3afc78b77-5556752b02ab9558.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:66) ~[fabric-networking-api-v1-1.3.9+b3afc78b77-5556752b02ab9558.jar:?]
	at net.minecraft.class_3324.handler$zei000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:3018) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:215) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$zej000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:27:07 INFO]: _Zulphiro lost connection: Invalid player data
[01:27:07 INFO]: _Zulphiro left the game
[01:27:07 WARN]: handleDisconnection() called twice
[01:30:51 INFO]: Unknown or incomplete command, see below for error

**Comment by maxomatic458** [comment]
I am able to reproduce it

temporary fix: give yourself OP before joining

**Comment by maxomatic458** [comment]
just fixed it, thanks for reporting.
I will create a new release for the bugfix.
